version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_EXT_INSTALL: pdo pdo_mysql mysqli
    image: apache-custom:latest # nomeie sua imagem personalizada, se desejar
    ports:
      - "80:80"
    volumes:
      - C:\Users\gabriel.leao\Pictures\api-dev:/var/www/html
    depends_on:
      - mysql
      - phpmyadmin
    command: sh -c "php artisan migrate --force && apache2-foreground"

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: my-secret-pw
